### ISSUE TITLE
Homebrew apps doesn't load when launched

### ISSUE THREAD

**Issue by Simo3ds** [Alexyo21/Polari3DS#22]
System type: Old 2DS v.11.17.0-50E
Version: CustomLuma3DS v1.0.1 
CustomLuma3DS settings enabled:
Enable loading external FIRMs and sysmodules
Enable Game Patching
Show NAND or user string in System Settings
Rosalina menu settings enabled: None

**Comment by Alexyo21** [comment]
Ok got it, but also when you disable game patching?

**Comment by Simo3ds** [comment]
lets check

**Comment by Simo3ds** [comment]
nothing
lets see if also without Enable loading external FIRMs and sysmodules work

**Comment by Simo3ds** [comment]
still nothing

**Comment by Simo3ds** [comment]
but i have to say it, normal app/NAND app seems to work normally

**Comment by Simo3ds** [comment]
ok, intresting, rverse work

**Comment by Simo3ds** [comment]
and in Nimbus they ask me to have Luma v13.0 or newer

**Comment by Alexyo21** [comment]
Uhm 
What 
The problem is on new consoles it work 
On old no
The version could be explained cause well the version is 1.0 ehhh😅

**Comment by Alexyo21** [comment]
So basically I cannot have a custom version🫠

**Comment by Simo3ds** [comment]
so bad for Old... i think that the only solution for old console is to have a custom version of everything but that support CustomLuma3DS but at that point, it will be an hard work

**Comment by Alexyo21** [comment]
That's a problem version version 
But I can put it back together to a superior version so pretendo app is working maybe fake a version

**Comment by Alexyo21** [comment]
Also I have to find this crappy bug so I can fix it

**Comment by Alexyo21** [comment]
It's always this way you  fix one and discover two... 2x1 sale

**Comment by Simo3ds** [comment]
Always lmao 😂

**Comment by Alexyo21** [comment]
Well cause most the code of the code was when I was learning so that explains...

**Comment by Simo3ds** [comment]
No problem, no one make perfection at the first time

**Comment by Alexyo21** [comment]
Right about It, 
Also I think i found it since rosalina is  culprit and the section to start hb launcher entry point is rosalina that is broken then also the ability of homebrew launcher Is indeed broken, so maybe fixing rosalina will fix also the hb loading
Not too much but something better than nothing

**Comment by Simo3ds** [comment]
Ok, thx

**Comment by Alexyo21** [comment]
should be addressed now though i had to separate that for now cause well lazyness....
