### ISSUE TITLE
Problem with N3DS clock rate / L2 config

### ISSUE THREAD

**Issue by The0zymandias** [Alexyo21/Polari3DS#26]
**System model:**

New 3DS

**SysNAND version (+emu/redNAND version if applicable):**

[e.g. 11.13.0-45U SysNAND, 11.13.0-45E EmuNAND]

**Entrypoint (How/what you're using to boot Luma3DS):**

Boot9Strap

**Luma3DS version:**

[e.g. v10.2 stable or if using non-releases specify the commit like this https://github.com/LumaTeam/Luma3DS/commit/0543c208fd154e6326ea5da8cbf66ffcbdef010c]

**Luma3DS configuration/options:**

Default EmuNAND: ( )

Screen brightness: ( )

Splash: ( )

Splash duration: ( )

PIN lock: ( )

New 3DS CPU: ( )

--

Autoboot EmuNAND: ( )

Use EmuNAND FIRM if booting with R: ( )

Enable loading external FIRMs and modules: ( )

Enable game patching: ( )

Show NAND or user string in System Settings: ( )

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

--

**Explanation of the issue:**

When the user tries to set the current title to always run with N3DS in the rosalina menu, it fails to create the config file unless luma/n3ds already exists. This could be fixed by creating the directory in N3DSMenu_CreateConfigFile in sysmodules/Rosalina/source/menus/n3ds.c.

**Steps to reproduce:**

1.

2.

**Dump file:**

**Comment by Alexyo21** [comment]
Hi, there thanks for making me noticing also I noticed that the file won't work on nand so I'm gonna add that also give it a few times I'm very busy at the moment

**Comment by Alexyo21** [comment]
It is fixed soon I will upload the code
Thanks a lot
